"""empty message

Revision ID: 7dadbae716c5
Revises: 
Create Date: 2023-07-12 20:44:06.823707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dadbae716c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sId')
        batch_op.drop_column('city')
        batch_op.drop_column('cId')
        batch_op.drop_column('billingAddress')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('phone_num')
        batch_op.drop_column('sub_day')
        batch_op.drop_column('country')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('scan')
        batch_op.drop_column('lastName')
        batch_op.drop_column('active')
        batch_op.drop_column('subscription')
        batch_op.drop_column('province')
        batch_op.drop_column('postalCode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postalCode', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('scan', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sub_day', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_num', sa.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('billingAddress', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cId', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sId', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
